---
- pipeline:
    name: Hello-World
    description: "Hello World Pipeline"
    manager: independent

- project-template:
    name: 00-SCS-template
    check:
      jobs:
        - 00-SCS/hello-world
        - 00-SCS/deploy

- secret:
    name: SECRET_TEST
    data:
      CREDENTIALS: !encrypted/pkcs1-oaep
        - BiqU95oqt1m2M9nGaxVDqUySzeNSqH5QZH7+CtbFGsWFJ1BjuJ65ZXtnVPdTdXK2HyMmv
          8FvNDKvc+Mt3VbwZ0bhK4eXgGov+pO2MLopr9EURumCAcDAFgStqiN32FYxWoEe65b7gh
          o5++8pYLJLqBHiLQaKKgYkiA0CGygLngswQzzUWzih88oHwV4Aidc3wwlobGopeB9g9QB
          31I/G3bNZqzEzT6sHFfGjESOrMqAq/+c2DSpkQezSfDwH9b2eEPaGGY9O7F6Oc+zhB/7g
          v/15HKePLTbxfmqxRHBPqhSh2yO71PzHckAli59EsBpJpvOsTbOzQXe6m0a4cDoXZOKUE
          WJmp6GcwJofDEcfviPAdorfMEFOVRmGgSl8HzTCmr81NhgLzeh+LJttid60v48xQvPbnc
          WYT9QBOhXlUbgWkNGZ1DPFh6eY1ygKqagu1wdBiSFVrJE50lqRSI7KMB1XMhlOJDs4KFY
          piN8LAKlRMlQiZXsZ3T3iHWBz2dbWYBmHCSsleJqjVJoEjZ+ysB1bgXHGzvktig2NdpoB
          QmSsfeU1HlVXB1p1HCdNrZScTT2bObPIzpnbzNyQsA8NAQxaerl1wUzIkMZw5rTMlZfsF
          ZxYqNQ8bWHvC2lOoZ3QRy1JpHA/z9hp4udDUoQL6BeqqAc07soskhHxBUiUTYw=

- semaphore:
    name: semaphore-hello-world
    max: 2

- job:
    name: 00-SCS/hello-world
    description: "Hello-World Job"
    # nodeset: ubuntu-jammy
    run: playbooks/hello-world.yaml
    required-projects:
      - opentelekomcloud-scs/testbed
    timeout: 10800
    secrets:
      - name: secret
        secret: SECRET_TEST 
    semaphores:
      - name: semaphore-hello-world

- job:
    name: 00-SCS/deploy
    description: "Deploy Job"
    # nodeset: ubuntu-jammy
    pre-run: playbooks/pre.yaml
    run: playbooks/deploy.yaml
    post-run: playbooks/post.yaml
    required-projects:
      - opentelekomcloud-scs/testbed
    timeout: 10800
    secrets:
      - name: secret
        secret: SECRET_TEST 
    semaphores:
      - name: semaphore-hello-world

- project:
    name: Hello-World-Project
    merge-mode: squash-merge    
    templates:
      - 00-SCS-template
