- project:
    merge-mode: squash-merge
    default-branch: main    
    check:
      jobs:
        - untrusted
    post:
      jobs:
        - check-nodepool 
    gate:
      jobs:
        - untrusted
    periodic-hourly:
      jobs:
        - untrusted
