- project:
    merge-mode: squash-merge
    check:
      jobs:
        - untrusted
        - check-repo
    gate:
      jobs:
        - untrusted
    periodic-hourly:
      jobs:
        - check-repo
