- project:
    merge-mode: squash-merge
    default-branch: main    
    check:
      jobs:
        - untrusted
        - check-nodepool
    post:
      jobs:
        - check-nodepool
    gate:
      jobs:
        - untrusted
    periodic-hourly:
      jobs:
        - untrusted
