---
- name: Check Repository for Recent Changes and Merge if Needed
  hosts: all
  gather_facts: true
  vars_files:
    - vars/repositories.yml  
  vars:
    ansible_galaxy: ~/venv/bin/ansible-galaxy
    ansible_path: "{{ basepath }}/ansible"
    ansible_playbook: ~/venv/bin/ansible-playbook  
    source_repo: "https://github.com/opentelekomcloud-scs/zuul-test"
    # target_repo: "https://github.com/opentelekomcloud-scs/zuul-test-src-repo"
    target_repo: "https://github.com/osism/testbed"
    basepath: "{{ ansible_user_dir }}/src/{{ repositories['testbed']['path'] }}"
    commit_message: "Automated merge of changes from source repo"
    repo_url: "https://api.github.com/repos/osism/testbed/commits"
    headers:
      Accept: "application/vnd.github.v3+json"
    time_limit: "{{ lookup('pipe', 'date --date=\"24 hours ago\" +%Y-%m-%dT%H:%M:%SZ') }}"
  tasks:
    # - name: Set facts (Zuul deployment)
    #   ansible.builtin.set_fact:
    #     cloud_env: "{{ cloud_envs[hostvars[groups['all'][0]]['nodepool']['label']] }}"
    #     is_zuul: true
    #     terragrunt_tfpath: "{{ ansible_user_dir }}/terraform"
    #   when: "'nodepool' in hostvars[groups['all'][0]]"

    # - name: Set facts (local deployment)
    #   ansible.builtin.set_fact:
    #     cloud_env: "{{ testbed_environment | default('ci') }}"
    #     is_zuul: false
    #     terragrunt_tfpath: terraform
    #   when: "'nodepool' not in hostvars[groups['all'][0]]"

    - name: Install jq
      become: true
      package:
        name: jq
        state: present

    - name: Fetch instance metadata
      become: true
      command: curl -s http://169.254.169.254/openstack/latest/meta_data.json
      register: metadata

    - name: Print instance metadata
      debug:
        msg: "{{ metadata.stdout | from_json }}"

    - name: Fetch user data
      become: true
      command: curl -s http://169.254.169.254/openstack/latest/user_data
      register: userdata

    - name: Print user data
      debug:
        msg: "{{ userdata.stdout }}"

    - name: Fetch network data
      become: true
      command: curl -s http://169.254.169.254/openstack/latest/network_data.json
      register: networkdata

    - name: Print network data
      debug:
        msg: "{{ networkdata.stdout | from_json }}"

    - name: Get the latest commits from the repository
      uri:
        url: "{{ repo_url }}"
        method: GET
        headers: "{{ headers }}"
        return_content: true
      register: repo_commits
 
    # - name: Debug
    #   debug:
    #     var: repo_commits

    - name: Wait for 7200 seconds (2 hours)
      wait_for:
        timeout: 7200

    - name: Check if there are any commits in the last 24 hours
      set_fact:
        changed: "{{ (repo_commits.json | selectattr('commit.committer.date', 'gt', time_limit) | list | count) > 0 }}"

    - name: Output the changed flag
      debug:
        msg: "Repository changed in the last 24 hours: {{ changed }}"

    - name: Execute playbooks if repository changed
      block:

        - name: Clone the testbed repository if changes detected
          ansible.builtin.git:
            repo: "{{ repositories['testbed']['repo'] }}"
            dest: "{{ basepath }}"
            clone: yes 
            update: no
          when: changed
          register: clone_target

        - name: Find all files and directories basepath
          ansible.builtin.find:
            paths: "{{ basepath }}/playbooks"
            recurse: yes
          register: files

        - name: Display all files and directories
          debug:
            msg: "{{ item.path }}"
          loop: "{{ files.files }}"

        - name: Execute pre-deployment playbook
          ansible.builtin.include_tasks: "{{ basepath }}/playbooks/pre.yaml"

        - name: Execute deployment playbook
          ansible.builtin.include_tasks: "{{ basepath }}/playbooks/deploy.yaml"

        - name: Execute post-deployment playbook
          ansible.builtin.include_tasks: "{{ basepath }}/playbooks/post.yaml"
        
        - name: Execute check playbook on successful deployment
          ansible.builtin.include_tasks: "{{ playbook_dir }}/check.yaml"
          
      when: changed
      rescue:
        - name: Handle errors in deployment scripts
          debug:
            msg: "An error occurred during the deployment process."

      always:
        - name: Execute cleanup playbook
          ansible.builtin.include_tasks: "{{ basepath }}/playbooks/cleanup.yaml"
