---
- name: pre.yaml
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Print pre.yaml message
      debug:
        msg: "--------------------------------------------------> pre.yaml"

    - name: Include hello_world.yaml
      include: hello_world.yaml
